web:
  build: .
  working_dir: /data
  command: python aulamvc.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5005:5005"

db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: 123456
  ports:
    - "3309:3309"
